services:
  logserver:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-logserver:${HAMSTRING_LOGSERVER_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    networks:
      hamstring:
    volumes:
      - ../../../config.yaml:/app/config.yaml
    environment:
      - GROUP_ID=log_storage
      - HAMSTRING_WAIT_FOR=kafka
  logcollector:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-logcollector:${HAMSTRING_LOGCOLLECTOR_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    environment:
      - GROUP_ID=log_collection
      - HAMSTRING_WAIT_FOR=kafka

  prefilter:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-prefilter:${HAMSTRING_PREFILTER_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=log_filtering
      - HAMSTRING_WAIT_FOR=kafka

  inspector:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-inspector:${HAMSTRING_INSPECTOR_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m
    environment:
      - GROUP_ID=data_inspection
      - NUMBER_OF_INSTANCES=1
      - HAMSTRING_WAIT_FOR=kafka

  detector:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-detector:${HAMSTRING_DETECTOR_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=data_analysis
      - HAMSTRING_WAIT_FOR=kafka

  detector-gpu:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-detector:${HAMSTRING_DETECTOR_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - GROUP_ID=data_analysis
      - HAMSTRING_WAIT_FOR=kafka
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  alerter:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-alerter:${HAMSTRING_ALERTER_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
      - "${ALERTER_LOGS_PATH:-/opt/logs}:/opt/logs"
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=data_alerting
      - HAMSTRING_WAIT_FOR=kafka
