services:
  monitoring_agent:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-monitoring:${HAMSTRING_MONITORING_IMAGE_TAG:-v2.2.0}"
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      - hamstring
    environment:
      GROUP_ID: monitoring_agent
      HAMSTRING_WAIT_FOR: kafka,clickhouse
      KAFKA_MAX_RECORD_BYTES: "${KAFKA_MAX_RECORD_BYTES:-}"
      KAFKA_TOPIC_PARTITIONS: "${KAFKA_TOPIC_PARTITIONS:-}"
      KAFKA_TOPIC_REPLICATION_FACTOR: "${KAFKA_TOPIC_REPLICATION_FACTOR:-}"
      CLICKHOUSE_USER: "${CLICKHOUSE_USER:-default}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD:-hamstring}"
