x-kafka-dependencies: &kafka-dependencies
  kafka1:
    condition: service_healthy
  kafka2:
    condition: service_healthy
  kafka3:
    condition: service_healthy

services:
  kafka1:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka1

  kafka2:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka2


  kafka3:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka3


  logserver:
    extends:
      file: "docker-compose.pipeline.yml"
      service: logserver
    depends_on: *kafka-dependencies

  logcollector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: logcollector
    depends_on: *kafka-dependencies


  prefilter:
    extends:
      file: "docker-compose.pipeline.yml"
      service: prefilter
    depends_on: *kafka-dependencies

  inspector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: inspector
    depends_on: *kafka-dependencies

  detector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: detector
    depends_on: *kafka-dependencies

  clickhouse-server:
    extends:
      file: "../base/docker-compose.clickhouse.yml"
      service: clickhouse-server

  grafana:
    extends:
      file: "../base/docker-compose.grafana.yml"
      service: grafana
    depends_on:
      clickhouse-server:
        condition: service_healthy

  prometheus:
    extends:
      file: "../base/docker-compose.prometheus.yml"
      service: prometheus

  kafka-exporter:
    extends:
      file: "../base/docker-compose.kafka-exporter.yml"
      service: kafka-exporter
    depends_on: *kafka-dependencies
  monitoring_agent:
    extends:
      file: "docker-compose.monitoring.yml"
      service: monitoring_agent
    depends_on:
      <<: *kafka-dependencies
      clickhouse-server:
        condition: service_healthy

networks:
  hamstring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

volumes:
  ch_data:
  ch_logs:
  kafka-broker-data1:
  kafka-broker-data2:
  kafka-broker-data3:
