apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse-server
      port: 9000

      protocol: native

      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
