services:
  kafka1:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka1

  kafka2:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka2


  kafka3:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka3
  clickhouse-server:
    extends:
      file: "docker-compose/base/docker-compose.clickhouse.yml"
      service: clickhouse-server

  grafana:
    extends:
      file: "docker-compose/base/docker-compose.grafana.yml"
      service: grafana

  prometheus:
    extends:
      file: "docker-compose/base/docker-compose.prometheus.yml"
      service: prometheus

  kafka-exporter:
    extends:
      file: "docker-compose/base/docker-compose.kafka-exporter.yml"
      service: kafka-exporter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy

  monitoring_agent-dev:
    extends:
      file: "docker-compose/dev/docker-compose.monitoring.yml"
      service: monitoring_agent
    profiles: ["dev", "dev-gpu"]

  monitoring_agent:
    extends:
      file: "docker-compose/prod/docker-compose.monitoring.yml"
      service: monitoring_agent
    profiles: ["prod", "prod-gpu"]

  logserver-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: logserver
    profiles: ["dev", "dev-gpu"]

  logserver:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: logserver
    profiles: ["prod", "prod-gpu"]

  logcollector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: logcollector
    profiles: ["dev", "dev-gpu"]


  logcollector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: logcollector
    profiles: ["prod", "prod-gpu"]

  prefilter-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: prefilter
    profiles: ["dev", "dev-gpu"]

  prefilter:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: prefilter
    profiles: ["prod", "prod-gpu"]

  inspector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: inspector
    profiles: ["dev", "dev-gpu"]

  inspector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: inspector
    profiles: ["prod", "prod-gpu"]


  detector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: detector
    profiles: ["dev"]

  detector-dev-gpu:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: detector-gpu
    profiles: ["dev-gpu"]

  detector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: detector
    profiles: ["prod"]

  detector-gpu:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: detector-gpu
    profiles: ["prod-gpu"]

  alerter-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: alerter
    profiles: ["dev", "dev-gpu"]

  alerter:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: alerter
    profiles: ["prod", "prod-gpu"]

  zeek:
    image: "${HAMSTRING_IMAGE_REGISTRY:-ghcr.io/astraos-de}/hamstring-zeek:${HAMSTRING_ZEEK_IMAGE_TAG:-2.0.4}"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - CONTAINER_NAME=zeek
      - HAMSTRING_ZEEK_KAFKA_WAIT_INTERVAL_SECONDS=${HAMSTRING_ZEEK_KAFKA_WAIT_INTERVAL_SECONDS:-5}
    volumes:
      - ../config.yaml:/opt/config.yaml
      - ../data/test_pcaps/:/opt/static_files
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      grafana:
        condition: service_healthy

networks:
  hamstring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

volumes:
  ch_data:
  ch_logs:
  kafka-broker-data1:
  kafka-broker-data2:
  kafka-broker-data3:
