services:
  logserver:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.logserver
    volumes:
      - ../../../config.yaml:/app/config.yaml
    environment:
      - GROUP_ID=log_storage
      - HAMSTRING_WAIT_FOR=kafka
    deploy:
      mode: "replicated"
      replicas: 1
    networks:
      hamstring:

  logcollector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.logcollector
    restart: "unless-stopped"
    deploy:
      mode: "replicated"
      replicas: 1
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    environment:
      - GROUP_ID=log_collection
      - HAMSTRING_WAIT_FOR=kafka
  prefilter:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.prefilter
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=log_filtering
      - HAMSTRING_WAIT_FOR=kafka
  inspector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.inspector
      network: host
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m
    environment:
      - GROUP_ID=data_inspection
      - NUMBER_OF_INSTANCES=1
      - HAMSTRING_WAIT_FOR=kafka
  detector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.detector
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=data_analysis
      - HAMSTRING_WAIT_FOR=kafka

  detector-gpu:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.detector
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - GROUP_ID=data_analysis
      - HAMSTRING_WAIT_FOR=kafka
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  alerter:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.alerter
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
      - "${ALERTER_LOGS_PATH:-../../../logs}:/opt/logs"
    networks:
      hamstring:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=data_alerting
      - HAMSTRING_WAIT_FOR=kafka
