services:
  kafka1:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka1

  kafka2:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka2


  kafka3:
    extends:
      file: "../base/docker-compose.kafka.yml"
      service: kafka3


  logserver:
    extends:
      file: "docker-compose.pipeline.yml"
      service: logserver

  logcollector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: logcollector


  prefilter:
    extends:
      file: "docker-compose.pipeline.yml"
      service: prefilter

  inspector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: inspector

  detector:
    extends:
      file: "docker-compose.pipeline.yml"
      service: detector

  clickhouse-server:
    extends:
      file: "../base/docker-compose.clickhouse.yml"
      service: clickhouse-server

  grafana:
    extends:
      file: "../base/docker-compose.grafana.yml"
      service: grafana

  prometheus:
    extends:
      file: "../base/docker-compose.prometheus.yml"
      service: prometheus

  kafka-exporter:
    extends:
      file: "../base/docker-compose.kafka-exporter.yml"
      service: kafka-exporter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
  monitoring_agent:
    extends:
      file: "docker-compose.monitoring.yml"
      service: monitoring_agent

networks:
  hamstring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

volumes:
  ch_data:
  ch_logs:
  kafka-broker-data1:
  kafka-broker-data2:
  kafka-broker-data3:
