{
 "title": "Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Granularity",
    "query": "SELECT CASE \n    WHEN (dateDiff('minute', toDateTime($__fromTime), toDateTime($__toTime))) <= 5 THEN 'Second'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 6 THEN 'Minute'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 72 THEN 'Hour'\n    ELSE 'Day'\nEND AS interval;"
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts per Time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOf${Granularity}(time_bucket) AS time_bucket,\n    sum(alert_count) AS \"count\"\nFROM alerts_1m\nWHERE time_bucket >= toStartOf${Granularity}(toDateTime($__fromTime))\n  AND time_bucket <= toStartOf${Granularity}(toDateTime($__toTime))\nGROUP BY time_bucket\nORDER BY time_bucket\nWITH FILL\nFROM toStartOf${Granularity}(toDateTime($__fromTime))\nTO toStartOf${Granularity}(toDateTime($__toTime))\nSTEP toInterval${Granularity}(1);"
    }
   ]
  },
  {
   "title": "Number of alerts in time range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM (\n  SELECT DISTINCT src_ip\n  FROM alerts\n  WHERE alert_timestamp >= $__fromTime AND alert_timestamp <= $__toTime\n);"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 } },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "# Alerts per day",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n    alert_month AS time,\n    sumIf(alert_count, day = 1) AS `1`,\n    sumIf(alert_count, day = 2) AS `2`,\n    sumIf(alert_count, day = 3) AS `3`,\n    sumIf(alert_count, day = 4) AS `4`,\n    sumIf(alert_count, day = 5) AS `5`,\n    sumIf(alert_count, day = 6) AS `6`,\n    sumIf(alert_count, day = 7) AS `7`,\n    sumIf(alert_count, day = 8) AS `8`,\n    sumIf(alert_count, day = 9) AS `9`,\n    sumIf(alert_count, day = 10) AS `10`,\n    sumIf(alert_count, day = 11) AS `11`,\n    sumIf(alert_count, day = 12) AS `12`,\n    sumIf(alert_count, day = 13) AS `13`,\n    sumIf(alert_count, day = 14) AS `14`,\n    sumIf(alert_count, day = 15) AS `15`,\n    sumIf(alert_count, day = 16) AS `16`,\n    sumIf(alert_count, day = 17) AS `17`,\n    sumIf(alert_count, day = 18) AS `18`,\n    sumIf(alert_count, day = 19) AS `19`,\n    sumIf(alert_count, day = 20) AS `20`,\n    sumIf(alert_count, day = 21) AS `21`,\n    sumIf(alert_count, day = 22) AS `22`,\n    sumIf(alert_count, day = 23) AS `23`,\n    sumIf(alert_count, day = 24) AS `24`,\n    sumIf(alert_count, day = 25) AS `25`,\n    sumIf(alert_count, day = 26) AS `26`,\n    sumIf(alert_count, day = 27) AS `27`,\n    sumIf(alert_count, day = 28) AS `28`,\n    sumIf(alert_count, day = 29) AS `29`,\n    sumIf(alert_count, day = 30) AS `30`,\n    sumIf(alert_count, day = 31) AS `31`\nFROM (\n    SELECT\n        toStartOfMonth(time_bucket) AS alert_month,\n        toDayOfMonth(time_bucket) AS day,\n        sum(alert_count) AS alert_count\n    FROM alerts_1m\n    WHERE time_bucket >= toStartOfMonth(now() - INTERVAL 1 YEAR)\n      AND time_bucket < toStartOfMonth(now())\n    GROUP BY alert_month, day\n) AS subquery\nGROUP BY alert_month\nORDER BY alert_month\nWITH FILL\nFROM toStartOfMonth(now() - INTERVAL 1 YEAR)\nTO toStartOfMonth(now())\nSTEP toIntervalMonth(1);"
    }
   ]
  },
  {
   "title": "# Alerts per hour",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n    alert_day AS time,\n    sumIf(alert_count, hour = 0) AS `0`,\n    sumIf(alert_count, hour = 1) AS `1`,\n    sumIf(alert_count, hour = 2) AS `2`,\n    sumIf(alert_count, hour = 3) AS `3`,\n    sumIf(alert_count, hour = 4) AS `4`,\n    sumIf(alert_count, hour = 5) AS `5`,\n    sumIf(alert_count, hour = 6) AS `6`,\n    sumIf(alert_count, hour = 7) AS `7`,\n    sumIf(alert_count, hour = 8) AS `8`,\n    sumIf(alert_count, hour = 9) AS `9`,\n    sumIf(alert_count, hour = 10) AS `10`,\n    sumIf(alert_count, hour = 11) AS `11`,\n    sumIf(alert_count, hour = 12) AS `12`,\n    sumIf(alert_count, hour = 13) AS `13`,\n    sumIf(alert_count, hour = 14) AS `14`,\n    sumIf(alert_count, hour = 15) AS `15`,\n    sumIf(alert_count, hour = 16) AS `16`,\n    sumIf(alert_count, hour = 17) AS `17`,\n    sumIf(alert_count, hour = 18) AS `18`,\n    sumIf(alert_count, hour = 19) AS `19`,\n    sumIf(alert_count, hour = 20) AS `20`,\n    sumIf(alert_count, hour = 21) AS `21`,\n    sumIf(alert_count, hour = 22) AS `22`,\n    sumIf(alert_count, hour = 23) AS `23`\nFROM (\n    SELECT\n        toStartOfDay(time_bucket) AS alert_day,\n        toHour(time_bucket) AS hour,\n        sum(alert_count) AS alert_count\n    FROM alerts_1m\n    WHERE time_bucket >= toStartOfMonth(now() - INTERVAL 1 MONTH)\n      AND time_bucket < toStartOfMonth(now())\n    GROUP BY alert_day, hour\n) AS subquery\nGROUP BY alert_day\nORDER BY alert_day\nWITH FILL\nFROM toStartOfMonth(now() - INTERVAL 1 MONTH)\nTO toStartOfMonth(now())\nSTEP toIntervalDay(1);"
    }
   ]
  },
  {
   "title": "# Alerts per quarter hour",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n    alert_hour AS time,\n    sumIf(alert_count, quarter = 0) AS `0`,\n    sumIf(alert_count, quarter = 1) AS `15`,\n    sumIf(alert_count, quarter = 2) AS `30`,\n    sumIf(alert_count, quarter = 3) AS `45`\nFROM (\n    SELECT\n        toStartOfHour(time_bucket) AS alert_hour,\n        intDiv(toMinute(time_bucket), 15) AS quarter,\n        sum(alert_count) AS alert_count\n    FROM alerts_1m\n    WHERE time_bucket >= toStartOfHour(now() - INTERVAL 1 DAY)\n      AND time_bucket <= now()\n    GROUP BY alert_hour, quarter\n) AS subquery\nGROUP BY alert_hour\nORDER BY alert_hour\nWITH FILL\nFROM toStartOfHour(now() - INTERVAL 1 DAY)\nTO toStartOfHour(now())\nSTEP toIntervalHour(1);"
    }
   ]
  },
  {
   "title": "Latest alerts and most active IP addresses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Latest 20 alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT src_ip AS \"Client IP address\", arrayStringConcat(JSONExtract(domain_names, 'Array(String)'), ', ') AS \"Domains used\"\nFROM alerts\nORDER BY alert_timestamp DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top 5 most active malicious addresses",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(rowNumberInAllBlocks() + 1, '.') AS \"Rank\",\n    src_ip AS \"Client IP address\",\n    count(logline_id) AS \"# Total Requests\"\nFROM loglines\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN (\n      SELECT DISTINCT src_ip\n      FROM alerts\n      WHERE alert_timestamp >= $__fromTime AND alert_timestamp <= $__toTime\n  )\nGROUP BY src_ip\nORDER BY \"# Total Requests\" DESC\nLIMIT 5;"
    }
   ]
  }
 ]
}