{
 "title": "Overview",
 "tags": [ "HAMSTRING" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "include_modules",
    "label": "Modules to include in comparison",
    "query": "LogServer : 'LogServer', Collector : 'Collector', BatchHandler : 'BatchHandler', Prefilter : 'Prefilter', Inspector : 'Inspector', Detector : 'Detector'"
   }
  ]
 },
 "panels": [
  {
   "title": "# Alerts per quarter hour",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    alert_hour AS time,\n    sumIf(alert_count, quarter = 0) AS `0`,\n    sumIf(alert_count, quarter = 1) AS `15`,\n    sumIf(alert_count, quarter = 2) AS `30`,\n    sumIf(alert_count, quarter = 3) AS `45`\nFROM (\n    SELECT\n        toStartOfHour(time_bucket) AS alert_hour,\n        intDiv(toMinute(time_bucket), 15) AS quarter,\n        sum(alert_count) AS alert_count\n    FROM alerts_1m\n    WHERE time_bucket >= toStartOfHour(now() - INTERVAL 1 DAY)\n      AND time_bucket <= now()\n    GROUP BY alert_hour, quarter\n) AS subquery\nGROUP BY alert_hour\nORDER BY alert_hour\nWITH FILL\nFROM toStartOfHour(now() - INTERVAL 1 DAY)\nTO toStartOfHour(now())\nSTEP toIntervalHour(1);"
    }
   ]
  },
  {
   "title": "Top 5 most active malicious addresses",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(toString(row_number() OVER (ORDER BY alert_count DESC, src_ip ASC)), '.') AS \"Rank\",\n    src_ip AS \"Client IP address\",\n    alert_count AS \"# Alerts\",\n    ifNull(total_requests, 0) AS \"# Total Requests\"\nFROM (\n    SELECT src_ip, count() AS alert_count\n    FROM alerts\n    WHERE alert_timestamp >= $__fromTime AND alert_timestamp <= $__toTime\n    GROUP BY src_ip\n) AS alert_counts\nLEFT JOIN (\n    SELECT src_ip, count() AS total_requests\n    FROM loglines\n    GROUP BY src_ip\n) AS request_counts USING src_ip\nORDER BY alert_count DESC, src_ip ASC\nLIMIT 5;"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 } },
  {
   "title": "Log volume combined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket AS timestamp,\n    avgMerge(avg_count) AS \" \"\nFROM fill_levels_1m\nWHERE stage = 'log_filtering.prefilter'\n  AND entry_type = 'total_loglines'\n  AND 'Prefilter' IN (${include_modules:csv})\n  AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket ASC;"
    },
    {
     "rawSql": "SELECT\n    time_bucket AS timestamp,\n    avgMerge(avg_count) AS \" \"\nFROM fill_levels_1m\nWHERE stage = 'data_inspection.inspector'\n  AND entry_type = 'total_loglines'\n  AND 'Inspector' IN (${include_modules:csv})\n  AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket ASC;"
    },
    {
     "rawSql": "SELECT\n    time_bucket AS timestamp,\n    avgMerge(avg_count) AS \" \"\nFROM fill_levels_1m\nWHERE stage = 'data_analysis.detector'\n  AND entry_type = 'total_loglines'\n  AND 'Detector' IN (${include_modules:csv})\n  AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket ASC;"
    },
    {
     "rawSql": "SELECT\n    time_bucket AS timestamp,\n    avgMerge(avg_count) AS \" \"\nFROM fill_levels_1m\nWHERE stage = 'log_collection.batch_handler'\n  AND entry_type = 'total_loglines_in_batches'\n  AND 'BatchHandler' IN (${include_modules:csv})\n  AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket ASC;"
    }
   ]
  },
  {
   "title": "Log volume comparison",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n  SELECT 'BatchHandler' AS name, quantileTDigestMerge(0.5)(median_count) AS \"Median\", 3 AS sort_order\n  FROM fill_levels_1m\n  WHERE stage = 'log_collection.batch_handler' AND entry_type = 'total_loglines_in_batches'\n    AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\n\n  UNION ALL\n\n  SELECT 'Prefilter' AS name, quantileTDigestMerge(0.5)(median_count) AS \"Median\", 4 AS sort_order\n  FROM fill_levels_1m\n  WHERE stage = 'log_filtering.prefilter' AND entry_type = 'total_loglines'\n    AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\n\n  UNION ALL\n\n  SELECT 'Inspector' AS name, quantileTDigestMerge(0.5)(median_count) AS \"Median\", 5 AS sort_order\n  FROM fill_levels_1m\n  WHERE stage = 'data_inspection.inspector' AND entry_type = 'total_loglines'\n    AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\n\n  UNION ALL\n\n  SELECT 'Detector' AS name, quantileTDigestMerge(0.5)(median_count) AS \"Median\", 6 AS sort_order\n  FROM fill_levels_1m\n  WHERE stage = 'data_analysis.detector' AND entry_type = 'total_loglines'\n    AND time_bucket >= $__fromTime AND time_bucket <= $__toTime\n)\nWHERE name IN (${include_modules:csv})\nORDER BY sort_order ASC;"
    }
   ]
  },
  {
   "title": "Latency comparison (per module)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\nSELECT 'LogServer' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM (\n    SELECT\n        sl.message_id AS message_id,\n        toDate(slt.event_timestamp) AS event_date,\n        sl.timestamp_in AS start_timestamp,\n        slt.event_timestamp AS end_timestamp,\n        dateDiff('microsecond', sl.timestamp_in, slt.event_timestamp) AS latency_us\n    FROM server_logs sl\n    INNER JOIN server_logs_timestamps slt ON sl.message_id = slt.message_id\n    WHERE slt.event = 'timestamp_out'\n      AND slt.event_timestamp > sl.timestamp_in\n) AS server_log_latency_values\nWHERE event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Collector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.collector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'BatchHandler' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.batch_handler'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Prefilter' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'log_filtering.prefilter'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Inspector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'data_inspection.inspector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Detector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM suspicious_batch_stage_latency_values\nWHERE stage = 'data_analysis.detector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n)\nWHERE name IN (${include_modules:csv});"
    }
   ]
  },
  {
   "title": "Latency comparison (per phase)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Data analysis phase' AS name, sum(median) AS median\nFROM (\nSELECT 'Inspector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'data_inspection.inspector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Detector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM suspicious_batch_stage_latency_values\nWHERE stage = 'data_analysis.detector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n)\n\nUNION ALL\n\nSELECT 'Data preparation phase' AS name, sum(median) AS median\nFROM (\nSELECT 'LogServer' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM (\n    SELECT\n        sl.message_id AS message_id,\n        toDate(slt.event_timestamp) AS event_date,\n        sl.timestamp_in AS start_timestamp,\n        slt.event_timestamp AS end_timestamp,\n        dateDiff('microsecond', sl.timestamp_in, slt.event_timestamp) AS latency_us\n    FROM server_logs sl\n    INNER JOIN server_logs_timestamps slt ON sl.message_id = slt.message_id\n    WHERE slt.event = 'timestamp_out'\n      AND slt.event_timestamp > sl.timestamp_in\n) AS server_log_latency_values\nWHERE event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'LogCollector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.collector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'BatchHandler' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.batch_handler'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Prefilter' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'log_filtering.prefilter'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n);"
    }
   ]
  },
  {
   "title": "Total latency",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'Including transport and wait time' AS name, sum(median) AS median\nFROM (\nSELECT 'LogServer' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM (\n    SELECT\n        sl.message_id AS message_id,\n        toDate(slt.event_timestamp) AS event_date,\n        sl.timestamp_in AS start_timestamp,\n        slt.event_timestamp AS end_timestamp,\n        dateDiff('microsecond', sl.timestamp_in, slt.event_timestamp) AS latency_us\n    FROM server_logs sl\n    INNER JOIN server_logs_timestamps slt ON sl.message_id = slt.message_id\n    WHERE slt.event = 'timestamp_out'\n      AND slt.event_timestamp > sl.timestamp_in\n) AS server_log_latency_values\nWHERE event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'LogCollection' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.collector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'BatchHandler' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.batch_handler'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Prefilter' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'log_filtering.prefilter'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Inspector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'data_inspection.inspector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Detector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM suspicious_batch_stage_latency_values\nWHERE stage = 'data_analysis.detector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Between BatchHandler and Prefilter' AS name, if(isFinite(median(value)), median(value), 0) AS median\nFROM (\n      SELECT dateDiff('microsecond', bt1.timestamp, bt2.timestamp) AS value\n      FROM batch_tree bt1\n      INNER JOIN batch_tree bt2\n              ON bt1.batch_row_id = bt2.parent_batch_row_id\n      WHERE bt1.stage = 'log_collection.batch_handler'\n        AND bt1.status = 'completed'\n        AND bt2.stage = 'log_filtering.prefilter'\n        AND bt2.status = 'in_process'\n        AND bt1.timestamp >= $__fromTime\n        AND bt2.timestamp <= $__toTime\n)\n\nUNION ALL\n\nSELECT 'Between Prefilter and Inspector' AS name, if(isFinite(median(value)), median(value), 0) AS median\nFROM (\n      SELECT dateDiff('microsecond', bt1.timestamp, bt2.timestamp) AS value\n      FROM batch_tree bt1\n      INNER JOIN batch_tree bt2\n              ON bt1.batch_row_id = bt2.parent_batch_row_id\n      WHERE bt1.stage = 'log_filtering.prefilter'\n        AND bt1.status = 'finished'\n        AND bt2.stage = 'data_inspection.inspector'\n        AND bt2.status = 'in_process'\n        AND bt1.timestamp >= $__fromTime\n        AND bt2.timestamp <= $__toTime\n)\n\nUNION ALL\n\nSELECT 'Between Inspector and Detector' AS name, if(isFinite(median(value)), median(value), 0) AS median\nFROM (\n      SELECT dateDiff('microsecond', bt1.timestamp, bt2.timestamp) AS value\n      FROM batch_tree bt1\n      INNER JOIN batch_tree bt2\n              ON bt1.batch_row_id = bt2.parent_batch_row_id\n      WHERE bt1.stage = 'data_inspection.inspector'\n        AND bt1.status = 'finished'\n        AND bt2.stage = 'data_analysis.detector'\n        AND bt2.status = 'in_process'\n        AND bt1.timestamp >= $__fromTime\n        AND bt2.timestamp <= $__toTime\n      AND dateDiff('microsecond', bt1.timestamp, bt2.timestamp) > 0\n)\n)\n\nUNION ALL\n\nSELECT 'Excluding transport and wait time' AS name, sum(median) AS median\nFROM (\nSELECT 'LogServer' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM (\n    SELECT\n        sl.message_id AS message_id,\n        toDate(slt.event_timestamp) AS event_date,\n        sl.timestamp_in AS start_timestamp,\n        slt.event_timestamp AS end_timestamp,\n        dateDiff('microsecond', sl.timestamp_in, slt.event_timestamp) AS latency_us\n    FROM server_logs sl\n    INNER JOIN server_logs_timestamps slt ON sl.message_id = slt.message_id\n    WHERE slt.event = 'timestamp_out'\n      AND slt.event_timestamp > sl.timestamp_in\n) AS server_log_latency_values\nWHERE event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'LogCollection' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.collector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'BatchHandler' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM logline_stage_latency_values\nWHERE stage = 'log_collection.batch_handler'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Prefilter' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'log_filtering.prefilter'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Inspector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM batch_stage_latency_values\nWHERE stage = 'data_inspection.inspector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n\nUNION ALL\n\nSELECT 'Detector' AS name, if(isFinite(median(latency_us)), median(latency_us), 0) AS median\nFROM suspicious_batch_stage_latency_values\nWHERE stage = 'data_analysis.detector'\n  AND event_date >= toDate($__fromTime) AND event_date <= toDate($__toTime)\n  AND end_timestamp >= $__fromTime AND end_timestamp <= $__toTime\n);"
    }
   ]
  }
 ]
}