services:
  prometheus:
    image: "${PROMETHEUS_IMAGE_REPOSITORY:-prom/prometheus}:${PROMETHEUS_IMAGE_TAG:-latest}"
    container_name: prometheus
    ports:
      - "9088:9090"
    volumes:
      - ../../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hamstring
