services:
  grafana:
    image: "${GRAFANA_IMAGE_REPOSITORY:-grafana/grafana}:${GRAFANA_IMAGE_TAG:-13.0.3-slim}"
    container_name: grafana
    networks:
      - hamstring
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - ../../grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../../grafana-provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../../grafana-provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-hamstring}
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3000" ]
      interval: 10s
      timeout: 5s
      retries: 3
